// AUTO-GENERATED by scripts/sync-design-tokens.mjs — do not edit by hand.
// Source: ../hire/design-system/tokens

export type GeneratedPalette = {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring: string;
  brand: string;
  brandForeground: string;
  brandStrong: string;
  brandMuted: string;
  brandRing: string;
  warning: string;
  warningForeground: string;
  warningStrong: string;
  warningMuted: string;
};

export const paletteLight: GeneratedPalette = {
  "background": "#fdfefc",
  "foreground": "#070707",
  "card": "#ffffff",
  "cardForeground": "#070707",
  "popover": "#ffffff",
  "popoverForeground": "#070707",
  "primary": "#070707",
  "primaryForeground": "#ffffff",
  "secondary": "#f0f0f0",
  "secondaryForeground": "#070707",
  "muted": "#f0f0f0",
  "mutedForeground": "#505050",
  "accent": "#e8e8e8",
  "accentForeground": "#070707",
  "destructive": "#e7000b",
  "destructiveForeground": "#fafafa",
  "border": "#e4e4e4",
  "input": "#e8e8e8",
  "ring": "#b2c248",
  "brand": "#5b6f00",
  "brandForeground": "#f3f6e2",
  "brandStrong": "#4c5c00",
  "brandMuted": "#e5eacd",
  "brandRing": "#b2c248",
  "warning": "#fe9a00",
  "warningForeground": "#461901",
  "warningStrong": "#bb4d00",
  "warningMuted": "#fef3c6"
};

export const paletteDark: GeneratedPalette = {
  "background": "#0d0e0b",
  "foreground": "#fafafa",
  "card": "#0c0c0c",
  "cardForeground": "#fafafa",
  "popover": "#181818",
  "popoverForeground": "#fafafa",
  "primary": "#fafafa",
  "primaryForeground": "#0c0c0c",
  "secondary": "#303030",
  "secondaryForeground": "#fafafa",
  "muted": "#1f1f1f",
  "mutedForeground": "#a4a4a4",
  "accent": "#262626",
  "accentForeground": "#fafafa",
  "destructive": "#ff6467",
  "destructiveForeground": "#0d0d0d",
  "border": "rgba(255, 255, 255, 0.08)",
  "input": "rgba(255, 255, 255, 0.12)",
  "ring": "#7b8847",
  "brand": "#9cae69",
  "brandForeground": "#101309",
  "brandStrong": "#b5c478",
  "brandMuted": "#2e3318",
  "brandRing": "#7b8847",
  "warning": "#ffb900",
  "warningForeground": "#461901",
  "warningStrong": "#ffb900",
  "warningMuted": "#461901"
};

export const spacing: Record<string, number> = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40,
  "12": 48,
  "16": 64,
  "20": 80,
  "24": 96
};

export const radius: Record<string, number> = {
  "DEFAULT": 10,
  "sm": 6,
  "md": 8,
  "lg": 10,
  "xl": 14
};
