#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# The Play Console and Google Cloud both move their UI around, so every stage
# opens a URL and then names the SECTION to look for rather than reciting a
# click path that may already be wrong. Where a page is only reachable by
# navigation, that is said plainly instead of guessed at.
PACKAGE="me.freehire.mobile"
GCP_PROJECT="freehire-mobile"

cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

banner "Google Play setup — freehire"

# ──────────────────────────────────────────────────────────────────────────
stage "Tooling"
say "Two CLIs do the parts that are not clicking. Checking them now, because"
say "finding out at stage 5 is worse than finding out here."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "✓ gh is authenticated — the last stage can set the repo variable itself."
else
  warn "gh is missing or not logged in. Stage 10 will tell you the command instead."
fi

if npx --no-install eas --version >/dev/null 2>&1 || command -v eas >/dev/null 2>&1; then
  say "✓ eas-cli is available."
else
  warn "eas-cli is not installed. Stages 4, 5 and 8 need it:"
  note "  npm i -g eas-cli && eas login"
fi
pause "Press Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "The question that costs two weeks"
say "Everything else here takes an afternoon. This one can take a fortnight,"
say "so it goes first — the clock can run while you do the rest."
open_url "https://play.google.com/console/"
step "Go to Settings (the gear) → Developer account → Account details."
step "Read two fields: the account TYPE, and the registration date."
ask PLAY_ACCOUNT_TYPE "Type the account type — personal or organisation:"

if [[ "$PLAY_ACCOUNT_TYPE" =~ ^[Pp] ]]; then
  warn "A personal account registered after 13 November 2023 cannot reach"
  warn "production until 20 testers have been in a CLOSED test for 14"
  warn "consecutive days. Internal testing does not count towards it."
  say ""
  step "If the registration date is after that: open Testing → Closed testing"
  step "and create a track now, before doing anything else in this wizard."
  note "Twenty real Google accounts, opted in, staying opted in for 14 days."
  pause "Press Enter once you know where you stand."
else
  say "✓ An organisation account has no 20-tester requirement."
  pause "Press Enter to continue."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Create the app record"
open_url "https://play.google.com/console/"
step "Press 'Create app'."
step "App name: freehire. Then: app (not game), free (not paid)."
say ""
note "The form does NOT ask for a package name, and that is not a mistake:"
note "Play takes the package from the FIRST bundle you upload. That happens in"
note "the next stage, and it is the moment $PACKAGE becomes permanent."
warn "A package name cannot be changed or reused afterwards. Not on this app,"
warn "not on any other, ever."
pause "Press Enter once the app record exists."

# ──────────────────────────────────────────────────────────────────────────
stage "Build the .aab, and upload it by hand"
say "Google refuses the first upload of a package name over the API, so this"
say "one upload is manual. Every later one is the CI job."
say ""
say "The .aab comes from the 'production' profile — 'preview' builds an APK for"
say "Firebase and Play will not take it."

if confirm "Run the EAS build now? (~20 minutes; skip if you already have an .aab)"; then
  npx eas build --platform android --profile production || \
    warn "The build failed or was interrupted. Re-run it yourself: npx eas build -p android --profile production"
else
  note "Skipped. Download the .aab from https://expo.dev when you have one."
fi

open_url "https://play.google.com/console/"
step "Open Testing → Internal testing → Create new release."
step "Upload the .aab. Confirm the package reads $PACKAGE."
pause "Press Enter once the bundle is uploaded."

# ──────────────────────────────────────────────────────────────────────────
stage "Service account #1 — for eas submit"
say "This one lets CI push builds. RevenueCat gets its OWN in the next stage;"
say "sharing one credential between them is how a revoked key breaks both."
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com?project=$GCP_PROJECT"
step "Enable the Google Play Android Developer API on project '$GCP_PROJECT'."
pause "Press Enter once it is enabled."

open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=$GCP_PROJECT"
step "Create a service account — name it something like 'play-submit-ci'."
step "Open it → Keys → Add key → Create new key → JSON. It downloads once."
ask PLAY_SA_EMAIL "Paste the service account email (…iam.gserviceaccount.com):"

open_url "https://play.google.com/console/"
step "Play Console → Settings → API access. Link the Google Cloud project"
step "'$GCP_PROJECT' if it is not linked yet."
step "Find $PLAY_SA_EMAIL there and grant it release permissions for this app."
note "It needs at least: view app information, and manage releases on the"
note "tracks you intend to publish to."
pause "Press Enter once the service account can release."

say ""
say "Now hand the JSON to EAS. This is interactive — it asks you to pick the"
say "file — so run it in this terminal after the wizard, or in another window:"
note "  npx eas credentials -p android"
note "  → production → Google Service Account → Manage → upload the JSON"
warn "The JSON stays on EAS, never in this repository. Delete the download"
warn "once EAS has it."
pause "Press Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "Service account #2 — for RevenueCat"
say "RevenueCat validates every purchase against Play and receives Play's"
say "webhooks. It needs its own credential to do that."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts?project=$GCP_PROJECT"
step "Create a second service account — 'revenuecat-play' or similar."
step "Keys → Add key → Create new key → JSON."
ask RC_SA_EMAIL "Paste this second service account's email:"

open_url "https://play.google.com/console/"
step "Settings → API access again. Grant $RC_SA_EMAIL access to this app."
note "RevenueCat's own docs list the permissions it needs; grant those rather"
note "than guessing, and expect Play to take a few hours to propagate them."
pause "Press Enter once granted."

open_url "https://app.revenuecat.com/"
step "Project settings → Apps → add the Google Play app for $PACKAGE."
step "Upload the JSON you just downloaded as its service account credential."
pause "Press Enter once RevenueCat has the credential."

# ──────────────────────────────────────────────────────────────────────────
stage "Subscriptions"
say "The App Store products do not carry over. Play needs its own, and"
say "RevenueCat needs to know they are the same thing as the iOS ones."
open_url "https://play.google.com/console/"
step "Monetise → Products → Subscriptions → Create subscription."
step "Make two, each with a base plan: one monthly, one yearly."
note "The iOS ids, for symmetry: me.freehire.mobile.pro.monthly and"
note "me.freehire.mobile.pro.annual. Play ids need not match iOS, and"
note "RevenueCat maps both onto one entitlement either way."
step "Activate the base plans — a draft subscription is invisible to the app."
pause "Press Enter once both exist and are active."

open_url "https://app.revenuecat.com/"
step "Add both Play products in RevenueCat, attach them to the SAME"
step "entitlement the iOS products use, and add them to the same offering."
warn "Same offering, or the paywall shows nothing on Android: the app renders"
warn "whatever packages the current offering holds and nothing else."
pause "Press Enter once the offering carries both platforms."

# ──────────────────────────────────────────────────────────────────────────
stage "The Android key into EAS"
say "Without this the build does not fail — it quietly ships unable to sell."
say "revenueCatKeys.js allows the key to be absent on purpose and only warns"
say "on the build log, so nothing on the device says anything is wrong."
open_url "https://app.revenuecat.com/"
step "Project settings → API keys → the PUBLIC key for the Google Play app."
step "It starts with goog_. Not the secret sk_ key, which belongs to a server."
ask EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "Paste the goog_ key:"

if [[ -n "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" && "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" != goog_* ]]; then
  warn "That does not start with goog_. app.config.ts will fail the build on it."
  warn "Nothing was saved; re-run this stage with the right key."
else
  write_env EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY"
  say ""
  say "Now put it in both EAS environments that build releases:"
  for env_name in preview production; do
    npx eas env:create --name EXPO_PUBLIC_REVENUECAT_ANDROID_KEY \
      --value "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" \
      --environment "$env_name" --visibility plaintext --non-interactive || \
      warn "Could not set it for '$env_name'. Do it by hand, or with eas env:update if it already exists."
  done
fi
pause "Press Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "The forms nobody enjoys"
say "Play will not publish until every one of these is answered. None of them"
say "is optional and none can be done from here."
open_url "https://play.google.com/console/"
step "Store listing: name, short and full description, icon, screenshots."
step "Content rating questionnaire."
step "Data safety — what the app collects and why."
step "Target audience and content, and the ads declaration (freehire has none)."
say ""
note "Data safety asks the same facts Apple's App Privacy did. Derive the"
note "answers from docs/app-store-privacy.md rather than answering twice from"
note "memory, and keep them consistent with the privacy manifest in"
note "app.config.ts — the two are compared."
note "Play's account-deletion requirement is already met: the app has a delete"
note "screen at src/app/account/delete.tsx."
pause "Press Enter once every section shows as complete."

# ──────────────────────────────────────────────────────────────────────────
stage "Turn the pipeline on"
say "Everything above happened outside this repository. This is the one thing"
say "that happens inside it: release.yml's 'Android → Google Play' job is"
say "gated on PLAY_SUBMIT_ENABLED and does nothing until it is 'true'."
say ""
say "Once on, every v* tag builds an .aab and submits it to the track named in"
say "eas.json — currently 'internal'."
warn "Do not turn this on before an .aab has been uploaded by hand and the"
warn "service account can release. It would put a red job on every tag."

if confirm "Has stage 4 (manual upload) and stage 5 (service account) really been done?"; then
  set_var PLAY_SUBMIT_ENABLED true
else
  SKIPPED+=("PLAY_SUBMIT_ENABLED (run: gh variable set PLAY_SUBMIT_ENABLED --body true)")
  note "Left off. Set it when the two are done."
fi

finish
